apiVersion : apps/v1
kind: Deployment
metadata:
  name: ning 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ning
  template:
    metadata:
      labels:
        app: ning 
    spec:
      containers:
        - name: ning 
          image: tony0416.azurecr.io/ning
          ports:
          - containerPort: 80